{{- range .Values.jobs }}
{{- $hasConfigFiles := and .configFiles (ne (len .configFiles) 0) -}}
{{- $tenxGitInit := or (and .config .config.git .config.git.enabled) (and .symbols .symbols.git .symbols.git.enabled) -}}
{{- $tenxVolumeInit := or (and .config .config.volume .config.volume.enabled) (and .symbols .symbols.volume .symbols.volume.enabled) -}}
{{- $tenxConfigEnabled := or $tenxGitInit $tenxVolumeInit -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "log10x-cron.fullname" $ }}-{{ .name }}
  labels:
    {{- include "log10x-cron.labels" $ | nindent 4 }}
spec:
  concurrencyPolicy: {{ .concurrencyPolicy | default "Allow" }}
  failedJobsHistoryLimit: {{ .failedJobsHistoryLimit | default 3 }}
  successfulJobsHistoryLimit: {{ .successfulJobsHistoryLimit | default 3 }}
  schedule: {{ .schedule | quote }}
  jobTemplate:
    spec:
      {{- if .activeDeadlineSeconds }}
      activeDeadlineSeconds: {{ .activeDeadlineSeconds }}
      {{- end }}
      template:
        metadata:
          {{- with $.Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          labels:
            app: {{ include "log10x-cron.name" $ }}
            log10x-cron-name: {{ include "log10x-cron.fullname" $ }}-{{ .name }}
        spec:
          {{- with $.Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "log10x-cron.serviceAccountName" $ }}
          {{- with .podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: {{ .restartPolicy | default "Never" }}
          {{- if or $tenxGitInit .initContainers }}
          initContainers:
          {{- with .initContainers }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if $tenxGitInit }}
            - name: tenx-git-config
              image: "{{ $.Values.configFetcherImage.repository }}:{{ $.Values.configFetcherImage.tag }}"
              imagePullPolicy: {{ $.Values.configFetcherImage.pullPolicy }}
              env:
                - name: GIT_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "log10x-cron.fullname" $ }}-git-token
                      key: token
              args:
                {{- if and .config .config.git .config.git.enabled }}
                - "--config-repo"
                - {{ .config.git.url | quote }}
                {{- if .config.git.branch }}
                - "--config-branch"
                - {{ .config.git.branch | quote }}
                {{- end }}
                {{- end }}
                {{- if and .symbols .symbols.git .symbols.git.enabled }}
                - "--symbols-repo"
                - {{ .symbols.git.url | quote }}
                {{- if .symbols.git.branch }}
                - "--symbols-branch"
                - {{ .symbols.git.branch | quote }}
                {{- end }}
                {{- if .symbols.git.path }}
                - "--symbols-path"
                - {{ .symbols.git.path | quote }}
                {{- end }}
                {{- end }}
              volumeMounts:
                - name: tenx-git
                  mountPath: /data
          {{- end }}
          {{- end }}
          containers:
          - image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
            imagePullPolicy: {{ $.Values.image.pullPolicy }}
            name: {{ .name }}
            env:
              - name: TENX_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: {{ $.Values.apiKeySecret.existingSecret | default (printf "%s-api-key" (include "log10x-cron.fullname" $)) }}
                    key: {{ $.Values.apiKeySecret.secretKey }}
            {{- if .runtimeName }}
              - name: TENX_RUNTIME_NAME
                value: "{{ .runtimeName }}"
            {{- end}}
            {{- if and .config .config.git .config.git.enabled }}
              - name: TENX_CONFIG
                value: "/etc/tenx/git/config"
            {{- else if and .config .config.volume .config.volume.enabled }}
              - name: TENX_CONFIG
                value: "/etc/tenx/config"
            {{- end }}
            {{- if and .symbols .symbols.git .symbols.git.enabled }}
              - name: TENX_SYMBOLS_PATH
                value: "/etc/tenx/git/config/data/shared/symbols"
            {{- else if and .symbols .symbols.volume .symbols.volume.enabled }}
              - name: TENX_SYMBOLS_PATH
                value: "/etc/tenx/symbols"
            {{- end }}
            {{- with .extraEnv }}
              {{- toYaml . | nindent 14 }}
            {{- end}}
            {{- if or .args $hasConfigFiles }}
            args:
            {{- with .args }}
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- range .configFiles }}
              - "@/etc/tenx/config/{{ .name }}"
            {{- end }}
            {{- end }}
            {{- with .resources }}
            resources:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with .containerSecurityContext }}
            securityContext:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- if or $tenxConfigEnabled .volumeMounts $hasConfigFiles }}
            volumeMounts:
            {{- if $tenxGitInit }}
              - name: tenx-git
                mountPath: /etc/tenx/git
            {{- end }}
            {{- if and .config .config.volume .config.volume.enabled }}
              - name: tenx-config-volume
                mountPath: /etc/tenx/config
            {{- end }}
            {{- if and .symbols .symbols.volume .symbols.volume.enabled }}
              - name: tenx-symbols-volume
                mountPath: /etc/tenx/symbols
            {{- end }}
            {{- range .configFiles }}
              - name: config-volume
                mountPath: /etc/tenx/config/{{ .name }}
                subPath: {{ .name }}
            {{- end }}
            {{- with .volumeMounts }}
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- end }}
            {{- with .nodeSelector }}
            nodeSelector:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with .affinity }}
            affinity:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with .tolerations }}
            tolerations:
              {{- toYaml . | nindent 14 }}
            {{- end }}
          {{- if or $tenxConfigEnabled .volumes $hasConfigFiles }}
          volumes:
          {{- if $tenxGitInit }}
            - name: tenx-git
              emptyDir: {}
          {{- end }}
          {{- if and .config .config.volume .config.volume.enabled }}
            - name: tenx-config-volume
              persistentVolumeClaim:
                claimName: {{ .config.volume.claimName }}
          {{- end }}
          {{- if and .symbols .symbols.volume .symbols.volume.enabled }}
            - name: tenx-symbols-volume
              persistentVolumeClaim:
                claimName: {{ .symbols.volume.claimName }}
          {{- end }}
          {{- if $hasConfigFiles }}
            - name: config-volume
              configMap:
                name: {{ include "log10x-cron.fullname" $ }}-{{ .name }}-config
          {{- end }}
          {{- with .volumes }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
---
{{- end }}
