{{- range .Values.jobs }}
{{- $hasConfigFiles := and .configFiles (ne (len .configFiles) 0) -}}
{{- $l1xGHInit := or .github.config .github.symbols -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "log10x-cron.fullname" $ }}-{{ .name }}
  labels:
    {{- include "log10x-cron.labels" $ | nindent 4 }}
spec:
  concurrencyPolicy: {{ .concurrencyPolicy | default "Allow" }}
  failedJobsHistoryLimit: {{ .failedJobsHistoryLimit | default 3 }}
  successfulJobsHistoryLimit: {{ .successfulJobsHistoryLimit | default 3 }}
  schedule: {{ .schedule | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          {{- with $.Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          labels:
            app: {{ include "log10x-cron.name" $ }}
            log10x-cron-name: {{ include "log10x-cron.fullname" $ }}-{{ .name }}
        spec:
          {{- with $.Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "log10x-cron.serviceAccountName" $ }}
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          restartPolicy: {{ .restartPolicy | default "Never" }}
          {{- if $l1xGHInit }}
          initContainers:
            - name: l1x-git-config
              image: ghcr.io/log-10x/github-config-fetcher:0.2.0
              args:
                {{- if .github.config }}
                - "--config-repo"
                - "https://{{ .github.config.token }}@github.com/{{ .github.config.repo }}.git"
                {{- if .github.config.branch }}
                - "--config-branch"
                - "{{ .github.config.branch }}"
                {{- end }}
                {{- end }}
                {{- if .github.symbols }}
                - "--symbols-repo"
                - "https://{{ .github.symbols.token }}@github.com/{{ .github.symbols.repo }}.git"
                {{- if .github.symbols.branch }}
                - "--symbols-branch"
                - "{{ .github.symbols.branch }}"
                {{- end }}
                {{- if .github.symbols.path }}
                - "--symbols-path"
                - "{{ .github.symbols.path }}"
                {{- end }}
                {{- end }}
              volumeMounts:
                - name: shared-git-volume
                  mountPath: /data
          {{- end }}
          containers:
          - image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
            imagePullPolicy: {{ $.Values.image.pullPolicy }}
            name: {{ .name }}
            env:
              - name: L1X_LICENSE
                value: "{{ $.Values.log10xLicense }}"
            {{- if .runtimeName }}
              - name: L1X_RUNTIME_NAME
                value: "{{ .runtimeName }}"
            {{- end}}
            {{- if .github.config }}
              - name: L1X_CONFIG
                value: "/etc/l1x/git/config"
            {{- end }}
            {{- if .github.symbols }}
              - name: L1X_SYMBOLS_PATH
                value: "/etc/l1x/git/config/data/shared/symbols"
            {{- end }}
            {{- with .extraEnv }}
              {{- toYaml . | nindent 14 }}
            {{- end}}
            {{- if or .args $hasConfigFiles }}
            args:
            {{- with .args }}
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- range .configFiles }}
              - "@/etc/l1x/config/{{ .name }}"
            {{- end }}
            {{- end }}
            {{- with .resources }}
            resources:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- if or $l1xGHInit .volumeMounts $hasConfigFiles }}
            volumeMounts:
            {{- if $l1xGHInit }}
              - name: shared-git-volume
                mountPath: /etc/l1x/git
            {{- end }}
            {{- range .configFiles }}
              - name: config-volume
                mountPath: /etc/l1x/config/{{ .name }}
                subPath: {{ .name }}
            {{- end }}
            {{- with .volumeMounts }}
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- end }}
            {{- with .nodeSelector }}
            nodeSelector:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with .affinity }}
            affinity:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with .tolerations }}
            tolerations:
              {{- toYaml . | nindent 14 }}
            {{- end }}
          {{- if or $l1xGHInit .volumes $hasConfigFiles }}
          volumes:
          {{- if $l1xGHInit }}
            - name: shared-git-volume
              emptyDir: {}
          {{- end }}
          {{- if $hasConfigFiles }}
            - name: config-volume
              configMap:
                name: {{ include "log10x-cron.fullname" $ }}-{{ .name }}-config
          {{- end }}
          {{- with .volumes }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
---
{{- end }}
