apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "log10x-quarkus.fullname" . }}-main
  labels:
    {{- include "log10x-quarkus.labels" . | nindent 4 }}
    app: {{ include "log10x-quarkus.name" . }}
    tier: main
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "log10x-quarkus.name" . }}
      tier: main
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "log10x-quarkus.name" . }}
        tier: main
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "log10x-quarkus.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if include "log10x-quarkus.githubEnabled" . }}
      initContainers:
        {{- include "log10x-quarkus.githubInitContainer" . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-main
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TENX_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.apiKeySecret.existingSecret | default (printf "%s-api-key" (include "log10x-quarkus.fullname" .)) }}
                  key: {{ .Values.apiKeySecret.secretKey }}
            - name: TENX_QUARKUS_MAX_ASYNC
              value: "{{ .Values.maxParallelRequests }}"
            - name: TENX_QUARKUS_MAX_QUEUED
              value: "{{ .Values.maxQueuedRequests }}"
            - name: TENX_QUARKUS_READINESS_THRESHOLD
              value: "{{ .Values.readinessThresholdPercent }}"
          {{- if and .Values.workers.enabled }}
            - name: TENX_WORKER_NAME
              value: '{{ include "log10x-quarkus.fullname" . }}-worker'
          {{- end }}
          {{- if and .Values.github .Values.github.config }}
            - name: TENX_CONFIG
              value: "/data/config"
          {{- end }}
          {{- if and .Values.github .Values.github.symbols }}
            - name: TENX_SYMBOLS_PATH
              value: "/data/config/data/shared/symbols"
          {{- end }}
          {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
          {{- end}}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if include "log10x-quarkus.githubEnabled" . }}
          volumeMounts:
            - name: github-data
              mountPath: /data
          {{- end }}
      {{- if include "log10x-quarkus.githubEnabled" . }}
      volumes:
        - name: github-data
          emptyDir: {}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- if and .Values.workers.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "log10x-quarkus.fullname" . }}-worker
  labels:
    {{- include "log10x-quarkus.labels" . | nindent 4 }}
    app: {{ include "log10x-quarkus.name" . }}
    tier: worker
spec:
  {{- if not .Values.workers.autoscaling.enabled }}
  replicas: {{ .Values.workers.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "log10x-quarkus.name" . }}
      tier: worker
  template:
    metadata:
      {{- with .Values.workers.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "log10x-quarkus.name" . }}
        tier: worker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "log10x-quarkus.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if include "log10x-quarkus.githubEnabled" $ }}
      initContainers:
        {{- include "log10x-quarkus.githubInitContainer" $ | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-worker
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TENX_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.apiKeySecret.existingSecret | default (printf "%s-api-key" (include "log10x-quarkus.fullname" $)) }}
                  key: {{ $.Values.apiKeySecret.secretKey }}
            - name: TENX_QUARKUS_MAX_ASYNC
              value: "{{ .Values.workers.maxParallelRequests }}"
            - name: TENX_QUARKUS_MAX_QUEUED
              value: "{{ .Values.workers.maxQueuedRequests }}"
            - name: TENX_QUARKUS_READINESS_THRESHOLD
              value: "{{ .Values.workers.readinessThresholdPercent }}"
            - name: TENX_WORKER_NAME
              value: {{ include "log10x-quarkus.fullname" . }}-worker
          {{- if and $.Values.github $.Values.github.config }}
            - name: TENX_CONFIG
              value: "/data/config"
          {{- end }}
          {{- if and $.Values.github $.Values.github.symbols }}
            - name: TENX_SYMBOLS_PATH
              value: "/data/config/data/shared/symbols"
          {{- end }}
          {{- with .Values.workers.extraEnv }}
            {{- toYaml . | nindent 12 }}
          {{- end}}
          ports:
            - name: http
              containerPort: {{ .Values.workers.service.containerPort }}
              protocol: TCP
          {{- with .Values.workers.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.workers.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.workers.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.workers.resources | nindent 12 }}
          {{- if include "log10x-quarkus.githubEnabled" $ }}
          volumeMounts:
            - name: github-data
              mountPath: /data
          {{- end }}
      {{- if include "log10x-quarkus.githubEnabled" $ }}
      volumes:
        - name: github-data
          emptyDir: {}
      {{- end }}
      {{- with .Values.workers.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.workers.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.workers.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
