apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "log10x-quarkus.fullname" . }}-main
  labels:
    {{- include "log10x-quarkus.labels" . | nindent 4 }}
    app: {{ include "log10x-quarkus.name" . }}
    tier: main
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "log10x-quarkus.name" . }}
      tier: main
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "log10x-quarkus.name" . }}
        tier: main
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "log10x-quarkus.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-main
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TENX_API_KEY
              value: "{{ $.Values.log10xApiKey }}"
            - name: TENX_QUARKUS_MAX_ASYNC
              value: "{{ .Values.maxParallelRequests }}"
            - name: TENX_QUARKUS_MAX_QUEUED
              value: "{{ .Values.maxQueuedRequests }}"
          {{- if and .Values.workers.enabled }}
            - name: TENX_WORKER_NAME
              value: '{{ include "log10x-quarkus.fullname" . }}-worker'
          {{- end }}
          {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
          {{- end}}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /hello
              port: http
          readinessProbe:
            httpGet:
              path: /hello
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- if and .Values.workers.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "log10x-quarkus.fullname" . }}-worker
  labels:
    {{- include "log10x-quarkus.labels" . | nindent 4 }}
    app: {{ include "log10x-quarkus.name" . }}
    tier: worker
spec:
  {{- if not .Values.workers.autoscaling.enabled }}
  replicas: {{ .Values.workers.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "log10x-quarkus.name" . }}
      tier: worker
  template:
    metadata:
      {{- with .Values.workers.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "log10x-quarkus.name" . }}
        tier: worker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "log10x-quarkus.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-worker
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TENX_API_KEY
              value: "{{ $.Values.log10xApiKey }}"
            - name: TENX_QUARKUS_MAX_ASYNC
              value: "{{ .Values.workers.maxParallelRequests }}"
            - name: TENX_QUARKUS_MAX_QUEUED
              value: "{{ .Values.workers.maxQueuedRequests }}"
            - name: TENX_WORKER_NAME
              value: {{ include "log10x-quarkus.fullname" . }}-worker
          {{- with .Values.workers.extraEnv }}
            {{- toYaml . | nindent 12 }}
          {{- end}}
          ports:
            - name: http
              containerPort: {{ .Values.workers.service.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /hello
              port: http
          readinessProbe:
            httpGet:
              path: /hello
              port: http
          resources:
            {{- toYaml .Values.workers.resources | nindent 12 }}
      {{- with .Values.workers.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.workers.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.workers.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
