{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "log10x-quarkus.fullname" . }}
  labels:
    {{- include "log10x-quarkus.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.log10xApiKey }}
  tenx-api-key: {{ .Values.log10xApiKey | b64enc | quote }}
  {{- end }}
{{- end }}
