# Default values for log10x-quarkus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Allows overriding base names
#
nameOverride: ""
fullnameOverride: ""

# License key is added to all containers via environment variable L1X_LICENSE
#
log10xLicense: "NO-LICENSE"

###### Image settings ######

image:
  repository: ghcr.io/log-10x/log10x-quarkus
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# When replacing the image to your own custom one, allows for setting
# secrets to allow pull access.
#
imagePullSecrets: []

###### Main deployment (outside world exposed entry points) ######

# Exposes the main deployment to rest calls
#
# If you want to expose the deployment directly (i.e. not via ingress)
# change the type to 'LoadBalancer'
#
service:
  type: ClusterIP
  port: 80
  containerPort: 8080

# Sets the static replica count.
# Value only used if 'autoscaling.enabled' is set to 'false'
#
replicaCount: 1

# Sets the maximum number of parallel pipelines each pod can execute
#
maxParallelRequests: 10

# Sets the maximum number of queued pipeline requests each pod can hold
#
maxQueuedRequests: 1000

# Allows adding additional environment variables to the pods
#
# Specific log10x pipelines might require some static changes to the environment
# variables for optimal performace.
#
# See http://doc.log10x.com/run/apps/cloud/ for more info on cloud applications
#
extraEnv: []

# Allows specifying resources for each pod
#
resources: {}

# Controls autoscaling via HorizontalPodAutoscaler
#
# For more info, see https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
#
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

###### Worker deployment (cluster only exposed entry points) ######

# Sets up a secondary deployment of pods to act as workers for the main deploymet
# Useful when there is a difference in the environment variables or resources
# between the main and worker pods
#
workers:
  enabled: false
  service:
    type: ClusterIP
    port: 80
    containerPort: 8080

  # Sets the static replica count.
  # Value only used if 'workers.autoscaling.enabled' is set to 'false'
  #
  replicaCount: 2

  # Sets the maximum number of parallel pipelines each pod can execute
  #
  maxParallelRequests: 10

  #  Sets the maximum number of queued pipeline requests each pod can hold
  #
  maxQueuedRequests: 1000

  # Allows adding additional environment variables to the pods
  #
  # Specific log10x pipelines might require some static changes to the environment
  # variables for optimal performace.
  #
  # See http://doc.log10x.com/run/apps/cloud/ for more info on cloud applications
  #
  extraEnv: []

  # Allows specifying resources for each pod
  #
  resources: {}

  # Controls autoscaling via HorizontalPodAutoscaler
  #
  # For more info, see https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
  #
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 20
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}
  tolerations: []
  affinity: {}

###### Service account ######

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

###### Annotations and security ######

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

###### Ingress ######

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
