{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "log10x-retriever.serviceAccountName" . }}
  labels:
    {{- include "log10x-retriever.labels" . | nindent 4 }}
  {{- with (include "log10x-retriever.serviceAccountAnnotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
{{- end }}
