# Default values for log10x-jobs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Allows overriding base names
#
nameOverride: ""
fullnameOverride: ""

# License key is added to all containers via environment variable L1X_LICENSE
#
log10xLicense: "NO-LICENSE"

###### Image settings ######

image:
  repository: ghcr.io/log-10x/log10x-pipeline
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# When replacing the image to your own custom one, allows for setting
# secrets to allow pull access.
#
imagePullSecrets: []

###### Jobs ######

jobs:
  - name: sample-pipeline
    # Run every 10 mintues
    schedule: "*/10 * * * *"
    args:
      - "run"
    # optional env vars
    # extraEnv:
    #   - name: MY_VAR
    #     value: "SOME_VALUE"
    configFiles:
      # - name: my-config.yaml
      #   content:
      #     my-key: my-value
    resources: {}
      # We usually recommend not to specify default resources and to leave this as a conscious
      # choice for the user. This also increases chances charts run on environments with little
      # resources, such as Minikube. If you do want to specify resources, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi
    securityContext: {}
      # capabilities:
      #   drop:
      #   - ALL
      # readOnlyRootFilesystem: true
      # runAsNonRoot: true
      # runAsUser: 1000
    nodeSelector: {}
    tolerations: []
    affinity: {}

podAnnotations: {}

###### Service account ######

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
