apiVersion: v2
description: Official Log10x helm chart for Quarkus-backed Log10x pipeline deployment
home: https://github.com/log-10x/helm-charts
maintainers:
  - email: dor.levi@log10x.com
    name: dor-levi
name: quarkus-10x
type: application
version: 0.5.7
appVersion: 0.30.6
