apiVersion: v1
kind: Service
metadata:
  name: {{ include "log10x-quarkus.fullname" . }}-main
  labels:
    {{- include "log10x-quarkus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: http
      targetPort: http
      protocol: TCP
  selector:
    app: {{ include "log10x-quarkus.name" . }}
    tier: main
{{- if and .Values.workers.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "log10x-quarkus.fullname" . }}-worker
  labels:
    {{- include "log10x-quarkus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.workers.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.workers.service.port }}
      name: http
      targetPort: http
      protocol: TCP
  selector:
    app: {{ include "log10x-quarkus.name" . }}
    tier: worker
{{- end }}
